;Program to display n factorial (iterative)
(defvar prod)
(defun fact (n)
	(setq prod 1) 
	(loop for i from 2 to n
		do(setq prod (* prod i)))
	(return-from  fact prod)
)
(defvar n)
(write-line "Enter n:")
(setf n (read))
(when (< n 0) (write-line "N cannot be less than 0!"))
(when (< n 0) (quit))
(write-line (format nil "~D factorial is :" n))
(write (fact n))
(terpri)
