;Program to display nth element of list
(defun nthele (n l)
	(when (= n 0) (return-from nthele (car l)))
	(nthele (- n 1) (cdr l)))
(defvar l)
(defvar n)
(write-line "Enter list :")
(setf l (read))
(write-line "Enter n (Starting 0) :")
(setf n (read))
(when (< n 0) (write-line "N cannot be less than 0!"))
(when (< n 0) (quit))
(write-line (format nil "Element ~D is :" n))
(write (nthele n l))
(terpri)
