;Program to display n factorial (recursive)
(defun fact (n)
	(when (= n 0) (return-from fact 1))
	(when (= n 1) (return-from fact 1))
	(return-from fact (* n (fact (- n 1)))))
(defvar n)
(write-line "Enter n:")
(setf n (read))
(when (< n 0) (write-line "N cannot be less than 0!"))
(when (< n 0) (quit))
(write-line (format nil "~D factorial is :" n))
(write (fact n))
(terpri)
